#!/bin/bash
# Session Resume Script - Generated October 15, 2025
# Quick environment restoration for NEST-FEST campaign continuation

echo "=========================================================================="
echo "NEST-FEST FACULTY OUTREACH CAMPAIGN - SESSION RESUME"
echo "=========================================================================="
echo ""
echo "Restoring session context for campaign deployment..."
echo ""

# Navigate to project directory
cd "D:\Portfolio\nest-fest-faculty-outreach"

# Display git status
echo "[1/5] Git Repository Status:"
git status
echo ""

# Check QR code file (CRITICAL BLOCKER)
echo "[2/5] Checking QR Code File (CRITICAL):"
if [ -f "assets/nest-fest-qr-code.png" ]; then
    echo "   [OK] QR code file present"
else
    echo "   [WARNING] QR code file MISSING at assets/nest-fest-qr-code.png"
    echo "   ACTION REQUIRED: Copy 1000x1000px QR code to this location"
fi
echo ""

# Run final QA check to verify 100% status maintained
echo "[3/5] Running Comprehensive QA Check:"
python final-qa-check.py 2>/dev/null || echo "   [INFO] QA script available for manual run"
echo ""

# Display current todos and priorities
echo "[4/5] Campaign Status & Next Actions:"
echo ""
echo "   CURRENT STATUS:"
echo "   ✅ 81 files verified (100% QA pass rate)"
echo "   ✅ 169 corrections applied"
echo "   ✅ Deployment ready"
echo ""
echo "   IMMEDIATE TASKS:"
echo "   1. [CRITICAL] Copy QR code to assets/nest-fest-qr-code.png"
echo "   2. [RECOMMENDED] Git commit and push all changes"
echo "   3. [RECOMMENDED] Test send one Tier 1 email to yourself"
echo "   4. [READY] Start sending Tier 1 critical emails (10 contacts)"
echo ""
echo "   CAMPAIGN TIMELINE:"
echo "   - Week 1 (START TODAY): Tier 1 emails (10 critical contacts)"
echo "   - Week 2: Tier 2 emails (10 high-priority) + follow-ups"
echo "   - Weeks 3-4: Tier 3 emails (42 general faculty)"
echo "   - Oct 30: Idea submission deadline"
echo "   - Nov 7: NEST-FEST event (2-6PM, Riverside)"
echo ""

# List key files for quick reference
echo "[5/5] Key Files for Campaign Execution:"
echo ""
echo "   DOCUMENTATION:"
echo "   - README.md - Campaign overview"
echo "   - QUICK_START_GUIDE.md - Fast implementation guide"
echo "   - DEPLOYMENT_READY_CERTIFICATE.md - Complete QA report"
echo "   - MASTER_EMAIL_TRACKING.md - Tracking and strategy"
echo ""
echo "   EMAILS TO SEND:"
echo "   - tier1-critical/*.txt (10 emails) - SEND FIRST"
echo "   - tier2-high/*.txt (10 emails) - Week 2"
echo "   - tier3-general/*.txt (42 emails) - Weeks 3-4"
echo ""
echo "   HTML ONE-PAGERS:"
echo "   - department-one-pagers/*.html (7 files)"
echo "   - Attach to emails or share via GitHub links"
echo ""
echo "   QA SCRIPTS (Reusable):"
echo "   - final-qa-check.py - Run anytime to verify consistency"
echo "   - All other scripts available for reference"
echo ""

# Display critical contact information
echo "=========================================================================="
echo "CRITICAL CAMPAIGN INFORMATION"
echo "=========================================================================="
echo ""
echo "EVENT DETAILS:"
echo "   Date: Thursday, November 7, 2025"
echo "   Time: 2:00-6:00 PM (2-5PM ceremonies, 5-6PM VIP reception)"
echo "   Location: Presentation Hall, ACC Riverside Campus"
echo "   Submission Deadline: October 30, 2025"
echo ""
echo "CONTACT INFORMATION:"
echo "   Abel Rincon: abel.rincon@g.austincc.edu | 737-206-9977"
echo "   Harshal Shah: harshal.shah@austincc.edu | 512-931-1791"
echo "   Dr. Andrea Kehoe: akehoe1@austincc.edu"
echo ""
echo "REQUIRED EMAIL CC (EVERY EMAIL):"
echo "   - harshal.shah@austincc.edu"
echo "   - akehoe1@austincc.edu"
echo ""
echo "EDGE LINKS (All Verified):"
echo "   Website: https://nest-fest.org/"
echo "   Discord: https://discord.gg/EgjuFMzV"
echo "   Student Org: https://austincc.campuslabs.com/engage/organization/edgeteam"
echo "   Calendar: https://calendar.app.google/rPFQ4o2k56fsKZrM6"
echo ""

# Recommended next commands
echo "=========================================================================="
echo "RECOMMENDED NEXT COMMANDS"
echo "=========================================================================="
echo ""
echo "# Verify QA status (optional):"
echo "python final-qa-check.py"
echo ""
echo "# Commit changes to git:"
echo "git add ."
echo "git commit -m \"Complete NEST-FEST faculty outreach - 100% QA verified\""
echo "git push origin master"
echo ""
echo "# Open first Tier 1 email to start campaign:"
echo "start tier1-critical/Means_Nina_EMAIL.txt"
echo ""
echo "=========================================================================="
echo "✅ Session context restored - Ready to launch campaign!"
echo "=========================================================================="
echo ""
echo "For detailed session information, see:"
echo "   .claude/sessions/2025-10-15_session/SESSION_SUMMARY.md"
echo ""
